version: "3.2"

networks:
  base-lite:

services:
  mysql:
    image: mysql:8.0.33
    container_name: database
    hostname: database
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - base-lite