server:
  port: 8080
  token_expire_time: 315360000
  token_secret: base-backend-lite

database:
  ip: xxx.xxx.xxx.xxx
  port: 8000
  username: root
  password: xxxxxx

validate_code:
  server: https://xxx
  appkey: xxxxxx
  appsecret: xxxxxx
  appcode: xxx

imtp:
  app_server: https://xxx
  api_server: https://xxx
  admin_private_key: xxx

logger:
  level: debug